### ISSUE TITLE
Error after selecting batch build for ZL17 or 18

### ISSUE THREAD

**Issue by Otter999** [stackTom/Ortho4XP_FSX_P3D#23]
I keep getting this error. Never had that in the version for FSX. Sometimes it works, but most of the time it doesn't. 
![error](https://user-images.githubusercontent.com/82292754/114312578-5ba1e880-9af3-11eb-8d58-36e508fe0c25.jpg)

**Comment by Otter999** [comment]
When switching to another tile and creating it at a lower zl and then coming back trying again, it sometimes work. Strange.

**Comment by stackTom** [comment]
I fixed this. It wasn't a freeze per se. Ortho4XP deselects the tile after it is finished. To rebuild it at a different ZL, it must be re-selected on the map. The problem was that I was showing the warning before checking to make sure a new tile had been selected, which gave users the impression that the program was frozen (it's not, just requires the user to select a tile).
